Build2017 new features
wangjun-microsoft/Cognitive-Face-Windows pull request #3
Opened 2017-03-23 05:17 UTC by sldi-microsoft

Support new attributes in detection for BUILD2017. 
Fix rotate image display bug.
Fix list person group and persons bug

2017-03-27 05:30 UTC, wangjun-microsoft commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> +
delete the blanks if convenient.

2017-03-27 05:33 UTC, wangjun-microsoft commented on Sample-WPF/Controls/FaceFindSimilarPage.xaml.cs
> +
delete the blanks

2017-03-27 05:33 UTC, wangjun-microsoft commented on Sample-WPF/Controls/FaceGroupingPage.xaml.cs
> +
delete the blanks

2017-03-27 05:33 UTC, wangjun-microsoft commented on Sample-WPF/Controls/FaceGroupingPage.xaml.cs
> +                            }
delete the blanks

2017-03-27 05:34 UTC, wangjun-microsoft commented on Sample-WPF/Controls/FaceVerificationPage.xaml.cs
> +                }
delete the blanks

2017-03-27 05:35 UTC, wangjun-microsoft commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> +
delete the blanks if convenient.

2017-03-27 05:36 UTC, wangjun-microsoft commented on Sample-WPF/Controls/FaceVerificationPage.xaml.cs
> +                            }
delete the blanks

2017-03-27 05:36 UTC, wangjun-microsoft commented on Sample-WPF/Controls/FaceVerificationPage.xaml.cs
> +                }
delete the blanks

2017-03-27 05:37 UTC, wangjun-microsoft approved these changes
with some comments

2017-03-27 08:26 UTC, wangjun-microsoft commented on ClientLibrary/FaceServiceClient.cs
> +        public async Task<Person[]> ListPersonsAsync(string personGroupId, string start = "", int top = 1000)
missing the function with only "top" parameter.

2017-03-27 08:27 UTC, wangjun-microsoft commented on ClientLibrary/FaceServiceClient.cs
> +        public async Task<Person[]> ListPersonsAsync(string personGroupId, string start = "", int top = 1000)
missing the function with only "top" parameter.

 public async Task<Person[]> ListPersonsAsync(string personGroupId, int top = 1000)

2017-03-27 08:28 UTC, wangjun-microsoft commented on ClientLibrary/FaceServiceClient.cs
> +        public async Task<Person[]> ListPersonsAsync(string personGroupId, string start = "", int top = 1000)
missing the function with only "top" parameter.

 public async Task<Person[]> ListPersonsAsync(string personGroupId, int top = 1000) 
{
      return await ListPersonsAsync(personGroupId, "", top); 
}

2017-03-28 03:40 UTC, huxuan requested changes
Ping me if you have any questions.

2017-03-28 03:40 UTC, huxuan commented on ClientLibrary/Contract/Exposure.cs
> +    using Newtonsoft.Json.Converters;
Extra empty line between `using` scope and class definition.

2017-03-28 03:40 UTC, huxuan commented on ClientLibrary/FaceServiceClient.cs
> +                top.ToString(CultureInfo.InvariantCulture));
Is the `.ToString(CultureInfo.InvariantCulture)` by purpose? Any reason?

2017-03-28 03:40 UTC, huxuan commented on ClientLibrary/FaceServiceClient.cs
> +        public async Task<Person[]> ListPersonsAsync(string personGroupId, int top)
I do not think this is necessary as `top` and `start` are optional parameters in ` ListPersonsAsync(string personGroupId, string start = "", int top = 1000)`.

2017-03-28 03:40 UTC, huxuan commented on ClientLibrary/IFaceServiceClient.cs
> +
I would suggest we keep the same order as it is in the API reference.

2017-03-28 03:40 UTC, huxuan commented on ClientLibrary/IFaceServiceClient.cs
> +        Task<PersonGroup[]> ListPersonGroupsAsync(int top);
Unnecessary duplicate in my point.

2017-03-28 03:40 UTC, huxuan commented on ClientLibrary/IFaceServiceClient.cs
> +        /// Gets 1000 persons inside a person group asynchronously.
What about just remove the `all` instead of specifying it as 1000 as the function itself is deprecated and we might change the number in the future.

2017-03-28 03:40 UTC, huxuan commented on ClientLibrary/IFaceServiceClient.cs
> +        Task<Person[]> ListPersonsAsync(string personGroupId, int top);
Please double check whether this is duplicate or not.

2017-03-28 03:40 UTC, huxuan commented on ClientLibrary/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.3.0")]
Please also remember to change other version number reference, e.g., `README.md`.

2017-03-28 03:40 UTC, huxuan commented on Sample-WPF/Controls/Face.cs
> +        /// <summary>
Again, same order as API reference. Also for the public attributes.

2017-03-28 03:40 UTC, huxuan commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> +
Please ensure this is done to ensure the overall basic code quality.

2017-03-28 03:40 UTC, huxuan commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> -                        MainWindow mainWindow = Window.GetWindow(this) as MainWindow;
Please have an extra check why there are so many `unchanged` changes.
Just to confirm no unexpected changes happen.

2017-03-28 03:40 UTC, huxuan commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> +                                Gender = face.FaceAttributes.Gender,
Order.

2017-03-28 03:40 UTC, huxuan commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> +                        maxConfidence = (float)hair.HairColor[i].Confidence;
What about just define the `Confidence` as `float` to avoid force conversion?

2017-03-28 03:40 UTC, huxuan commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> +            return "Accessories: "+ accessoriesType;
I suggest we use `String.Join()` [1] instead of raw concatenation.

[1] https://msdn.microsoft.com/en-us/library/57a79xd0(v=vs.110).aspx

2017-03-28 03:40 UTC, huxuan commented on Sample-WPF/Controls/FaceVerificationPage.xaml.cs
> +
Please avoid this kind of redundant spaces.

2017-03-28 07:21 UTC, sldi-microsoft commented on ClientLibrary/Contract/Exposure.cs
> +    using Newtonsoft.Json.Converters;
Fix it

2017-03-28 07:22 UTC, sldi-microsoft commented on ClientLibrary/IFaceServiceClient.cs
> +
Fix it.

2017-03-28 07:22 UTC, sldi-microsoft commented on ClientLibrary/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.3.0")]
Yeah, already check.

2017-03-28 07:22 UTC, sldi-microsoft commented on Sample-WPF/Controls/Face.cs
> +        /// <summary>
Fix it.

2017-03-28 08:21 UTC, huxuan requested changes

2017-03-28 08:21 UTC, huxuan commented on ClientLibrary/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.3.0")]
Please check `Sample-WPF/FaceAPI-WPF-Samples.csproj` again.

2017-03-28 08:21 UTC, huxuan commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> +
Please remove it.

2017-03-28 08:21 UTC, huxuan commented on Sample-WPF/Controls/FaceVerificationPage.xaml.cs
> +                }
Please remove the redundant spaces.

2017-03-28 08:21 UTC, huxuan commented on Sample-WPF/Controls/FaceVerificationPage.xaml.cs
> +
Ditto.

2017-03-28 08:21 UTC, huxuan commented on Sample-WPF/Controls/FaceVerificationPage.xaml.cs
> +                            }
Ditto.

2017-03-28 08:21 UTC, huxuan commented on Sample-WPF/Controls/FaceVerificationPage.xaml.cs
> +                }
Ditto.

2017-03-28 08:42 UTC, sldi-microsoft commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> +
Fix it

2017-03-28 08:42 UTC, sldi-microsoft commented on Sample-WPF/Controls/FaceDetectionPage.xaml.cs
> +
Fix it

2017-03-28 08:42 UTC, sldi-microsoft commented on Sample-WPF/Controls/FaceVerificationPage.xaml.cs
> +                }
Fix it

2017-03-28 08:44 UTC, sldi-microsoft commented on ClientLibrary/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.3.0")]
Fix it

2017-03-28 09:01 UTC, huxuan approved these changes

2017-03-29 06:02 UTC, GangChenMSFT commented on ClientLibrary/Contract/Blur.cs
> +    /// Face BLur class contains blur information
BLur=> Blur spelling case error.

2017-03-29 06:04 UTC, GangChenMSFT commented on ClientLibrary/Contract/Blur.cs
> +        /// Get or set value for Blur
ranges from 0..1.0, which 0 indicates no blur and clear faces, 1.0 indicates extremely blur. Normally 0.??? (please confirm Wenbin) indicates low, ??? for medium, and ??? for high.

2017-03-29 06:05 UTC, GangChenMSFT commented on ClientLibrary/Contract/Exposure.cs
> +        /// Get or set value for Exposure
Missing value range description.

2017-03-29 06:06 UTC, GangChenMSFT commented on ClientLibrary/Contract/Hair.cs
> +    public enum ColorType
HairColorType?

2017-03-29 06:07 UTC, GangChenMSFT commented on ClientLibrary/Contract/Hair.cs
> +        /// Get or set Bald value
The confidence of a bald head (no hair)

2017-03-29 06:08 UTC, GangChenMSFT commented on ClientLibrary/Contract/Hair.cs
> +        /// Get or set hair invisible
Explain the "invisible" because of being occluded. Not of being bald.

2017-03-29 06:09 UTC, GangChenMSFT commented on ClientLibrary/Contract/Hair.cs
> +        /// Get or set HairColor array
Indicating ALL possible hair colors or the top matches?

2017-03-29 06:13 UTC, GangChenMSFT commented on ClientLibrary/Contract/Makeup.cs
> +        public bool EyeMakeup
missing confidence?

2017-03-29 06:14 UTC, GangChenMSFT commented on ClientLibrary/Contract/Makeup.cs
> +        public bool LipMakeup
missing confidence?

2017-03-29 06:14 UTC, GangChenMSFT commented on ClientLibrary/Contract/Noise.cs
> +        /// Low level
Low noise level indicating a clear face image.

2017-03-29 06:15 UTC, GangChenMSFT commented on ClientLibrary/Contract/Occlusion.cs
> +        /// Get or set ForeheadOccluded
true for occluded.

2017-03-29 08:11 UTC, sldi-microsoft commented on ClientLibrary/Contract/Blur.cs
> +    /// Face BLur class contains blur information
Fix it.

2017-03-29 08:14 UTC, sldi-microsoft commented on ClientLibrary/Contract/Blur.cs
> +    /// Face BLur class contains blur information
By the way, Face API doesn't return confidence of makeup, so I don't add this property.

2017-03-30 08:03 UTC, closed without merging